# Copyright (c) Huawei Technologies Co., Ltd. 2025-2026. All rights reserved.
# Description: makefile for enclave
# Author: zhongjiawei
# Create: 2025-03-20

all:qt-enclave

qt-enclave:
	@go build -o qt-enclave-exporter main.go
