# Copyright (c) Huawei Technologies Co., Ltd. 2025-2026. All rights reserved.
# Description: makefile for enclave
# Author: liuxu
# Create: 2025-03-20

all:qt-device-plugin
 
qt-device-plugin:
	@go build -o qt-enclave-k8s-device-plugin